HOUSES_INDEX = 0
OPPONENT_SPACE_INDEX = 1
RENT_INDEX = 2
PLAYER_MONEY_INDEX = 3
OPPONENT_MONEY_INDEX = 4

INITIAL_NUM_HOUSES = 1
AGENT_STARTING_MONEY = 1500
OPPONENT_STARTING_MONEY = 1500

GO_TO_JAIL_COST = 50
INCOME_TAX_COST = 200
LUXURY_TAX_COST = 100

JAIL_POSITION = 10

BATCH_SIZE = 256
MAX_EXPERIENCE_LEN = 5120
GAMMA = .9